### PR TITLE
Re-arrange the layout to 2 columns

### PR DESCRIPTION
**Pull request by thanhnew2001**
- Re-arrange the layout to 2 columns
- Add a "New chat" button which will show all tips, hints etc.
- Add past prompts pane (still couldn't manage to refresh the list of prompts)

### CODE REVIEW

**Comment by thanhnew2001** [comment]
Hello Alex,

Following the work yesterday, I made some minor changes to the layout. Please help review it
- 2 columns layout
- New chat button
- Past prompt panel (prompt history)

**Comment by thanhnew2001** [comment]
Hi Alex, 
I just added another fix on column labels. 
Please consider to merge this change as well
Best regards
Thanh

**Comment by AlexandreSajus** [comment]
I really like the new layout; it looks way better than what I did.

There still are some issues:
- Wordninja on the column names is a good idea, but it is not called when the user uploads a new dataset
- Maybe these 3 expendable tabs should be regrouped in the same expandable tab. They should also be always accessible so the user can read tips and examples even after his prompt:
image
- The prompt history does not work currently, and the functions of "Reset App" and "New Chat" are unclear

**Comment by AlexandreSajus** [comment]
Copied to #50

**Pull request closed without merging**
